-- AlterTable
ALTER TABLE `categories` ADD COLUMN `color` VARCHAR(191) NULL,
    ADD COLUMN `icon` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `users` ADD COLUMN `Role` ENUM('FREE', 'PRO') NOT NULL DEFAULT 'FREE';
